### ISSUE TITLE
DRY a bit more in the purging methods

### ISSUE THREAD

**Issue by robbieaverill** [steadlane/silverstripe-cloudflare#12]
It'd be nice to see the purging methods be centralised a little bit more. In my opinion, you have two types of purge request:

* Everything
* Specific file(s)

In the case of `purgeSingle` and `purgeMany`, `purgeSingle` could be simply `return $this->purgeMany(array($url))`.

In the case of the JS, CSS, image purge methods - they should use some centralised logic to find the relevant files and normalise their paths, then use the same `purgeMany(array $urls)` method to control the actual purging.

**Comment by zanderwar** [comment]
I completely agree, I work this in as soon as possible. Due for a new tag soon anyway

**Comment by zanderwar** [comment]
WIP #18
