### ISSUE TITLE
ZoneID error

### ISSUE THREAD

**Issue by Firesphere** [steadlane/silverstripe-cloudflare#46]
The request to find the zone ID is returning no results.

However, I'm sure I have the correct credentials. Is there any way to debug this problem?

**Comment by tim-mediasuite** [comment]
You can use something like 
`curl -X GET "https://api.cloudflare.com/client/v4/zones/" \
     -H "Content-Type:application/json" \
     -H "X-Auth-Key:somekey" \
     -H "X-Auth-Email:example@example.com"`

to figure out whether it's the credentials or the module.

**Comment by Firesphere** [comment]
Turns out that it was a Cloudflare/cache issue... :man_facepalming:
